platform=ANDROID

deviceName=Pixel_7
platformVersion=14
automationName=UiAutomator2

# App location
app=apps/android/sauce-demo.apk

# Android specific
appPackage=com.saucelabs.mydemoapp.rn
appActivity=com.saucelabs.mydemoapp.rn.MainActivity

# iOS specific
bundleId=com.saucelabs.mydemoapp.rn

# Appium
appiumServerUrl=http://127.0.0.1:4723

explicitWait=20
threads=2
